export const getLocalizedText = (item, field, lang) => {
  const localizedField = `${field}_${lang}`;
  return item?.[localizedField] || item?.[field] || '';
};

export const texts = {
  ar: {
    home: 'الرئيسية',
    about: 'من نحن',
    services: 'الخدمات',
    departments: 'الإدارات',
    blog: 'المدونة',
    join: 'إنضم إلينا',
    contact: 'تواصل معانا',
    exploreServices: 'استكشف خدماتنا',
    exploreBLogs: 'استكشف المقالات',
    contactUs: 'تواصل معنا',
    knowMore: 'تعرف علينا',
    arabic: 'العربية',
    english: 'English',
    siteMap: 'خريطة الموقع',
    contactInfo: 'معلومات التواصل',
    followUs: 'تابعنا علي',
    copyright: 'جميع الحقوق محفوظة © شركة أراف للخدمات الصحية المنزلية 2026',
    privacy: 'سياسة الخصوصية',
    terms: 'شروط الاستخدام',
    companyDescription: 'نقدّم خدمات رعاية صحية منزلية موثوقة باحترافية وجودة عالية، لنمنح مرضانا رعاية متكاملة داخل منازلهم بكل راحة وأمان.',
    whyJoinTOUs: 'هل تريد الانضمام لفريقنا؟',
    whyJoinTOUsDescription: 'نبحث دائماً عن المواهب المتميزة للانضمام إلى فريقنا',
    // Form keys
    together: 'معًا',
    whyJoinUs: 'لماذا تنضم إلينا؟',
    joinUsDescription: 'انضم لفريقنا في الرعاية الصحية المنزلية وكن جزءًا من بيئة عمل ملهمة، تضمن لك التطور المهني، الدعم المستمر، وفرص حقيقية للنمو.',
    applyNow: 'قدم الآن',
    nameLabel: 'الاسم',
    phoneLabel: 'الهاتف',
    jobTitleLabel: 'الوظيفة',
    messageLabel: 'الرسالة',
    namePlaceholder: 'أدخل اسمك',
    phonePlaceholder: 'أدخل رقم الهاتف',
    jobPlaceholder: 'ادخل نوع الوظيفة',
    messagePlaceholder: 'اكتب رسالتك',
    uploadCvPdf: 'رفع السيرة الذاتية (PDF)',
    uploadFilesOptional: 'إرفاق ملفات (اختياري)',
    clickToUpload: 'اضغط لرفع ملفات',
    multipleFiles: 'بإمكانك ارفاق عدة ملفات',
    submit: 'إرسال',
    sendMessage: 'أرسل لنا رسالة',
    saudiCode: '966+',
    fillName: 'املأ الاسم',
    fillPhone: 'املأ الهاتف',
    numbersOnly: 'أدخل أرقام فقط',
    phoneNineDigits: 'يجب أن يكون الرقم 9 أرقام بالضبط',
    fillJob: 'املأ الوظيفة',
    fillMessage: 'املأ الرسالة',
    requestReceived: 'لقد تلقينا طلبك',
    messageReceived: 'لقد تلقينا رسالتك',
    teamWillContact: 'فريقنا سوف يتواصل معك قريباً',
    riyadhAddress: 'الرياض، المملكة العربية السعودية',
    // Care component keys
    reliableCare: 'رعاية موثوقة',
    safeServices: 'خدمات صحية منزلية آمنة وموثوقة لجميع عملائنا.',
    qualitySafety: 'جودة وأمان أولويتنا',
    highStandards: 'نلتزم بأعلى معايير الجودة والسلامة في كل خدمة.',
    constantCommunication: 'تواصل دائم وسريع',
    quickResponse: 'استجابة فعالة وسريعة لجميع احتياجات المرضى وعائلاتهم.',
    continuousDevelopment: 'تطوير مستمر',
    latestTech: 'نحرص على تطوير خدماتنا باستمرار باستخدام أحدث التقنيات الطبية'
  },
  en: {
    home: 'Home',
    about: 'About',
    services: 'Services',
    departments: 'Departments',
    blog: 'Blog',
    join: 'Join Us',
    contact: 'Contact Us',
    exploreServices: 'Explore Our Services',
    exploreBLogs: 'Explore Our Blogs',
    contactUs: 'Contact Us',
    knowMore: 'Know More',
    arabic: 'Arabic',
    english: 'English',
    siteMap: 'Site Map',
    contactInfo: 'Contact Information',
    followUs: 'Follow Us',
    copyright: 'All Rights Reserved © Araf Home Healthcare Services 2026',
    privacy: 'Privacy Policy',
    terms: 'Terms of Use',
    companyDescription: 'We provide reliable home healthcare services with professionalism and high quality, to give our patients comprehensive care inside their homes with comfort and safety.',
    whyJoinTOUs: 'Do you want to join our team?',
    whyJoinTOUsDescription: 'We are always looking for outstanding talent to join our team',
    // Form keys
    together: 'Together',
    whyJoinUs: 'Why Join Us?',
    joinUsDescription: 'Join our home healthcare team and be part of an inspiring work environment that ensures your professional development, continuous support, and real growth opportunities.',
    applyNow: 'Apply Now',
    nameLabel: 'Name',
    phoneLabel: 'Phone',
    jobTitleLabel: 'Job Title',
    messageLabel: 'Message',
    namePlaceholder: 'Enter your name',
    phonePlaceholder: 'Enter phone number',
    jobPlaceholder: 'Enter job type',
    messagePlaceholder: 'Write your message',
    uploadCvPdf: 'Upload CV (PDF)',
    uploadFilesOptional: 'Attach files (optional)',
    clickToUpload: 'Click to upload files',
    multipleFiles: 'You can attach multiple files',
    submit: 'Submit',
    sendMessage: 'Send us a message',
    saudiCode: '966+',
    fillName: 'Fill name',
    fillPhone: 'Fill phone',
    numbersOnly: 'Enter numbers only',
    phoneNineDigits: 'Phone must be exactly 9 digits',
    fillJob: 'Fill job title',
    fillMessage: 'Fill message',
    requestReceived: 'We received your request',
    messageReceived: 'We received your message',
    teamWillContact: 'Our team will contact you soon',
    riyadhAddress: 'Riyadh, Kingdom of Saudi Arabia',
    // Care component keys
    reliableCare: 'Reliable Care',
    safeServices: 'Safe and reliable home healthcare services for all our clients.',
    qualitySafety: 'Quality and Safety are Our Priority',
    highStandards: 'We adhere to the highest standards of quality and safety in every service.',
    constantCommunication: 'Constant and Fast Communication',
    quickResponse: 'Effective and quick response to all patients and their families needs.',
    continuousDevelopment: 'Continuous Development',
    latestTech: 'We continuously develop our services using the latest medical technologies'
  }
};

