export const getLocalizedText = (item, field, lang) => {
  const localizedField = `${field}_${lang}`;
  return item?.[localizedField] || item?.[field] || '';
};

export const texts = {
  ar: {
    home: 'الرئيسية',
    about: 'من نحن',
    services: 'الخدمات',
    departments: 'الإدارات',
    blog: 'المدونة',
    join: 'إنضم إلينا',
    contact: 'تواصل معانا',
    exploreServices: 'استكشف خدماتنا',
    exploreBLogs: 'استكشف المقالات',
    contactUs: 'تواصل معنا',
    knowMore: 'تعرف علينا',
    arabic: 'العربية',
    english: 'English',
    siteMap: 'خريطة الموقع',
    contactInfo: 'معلومات التواصل',
    followUs: 'تابعنا علي',
    copyright: 'جميع الحقوق محفوظة © شركة أراف للخدمات الصحية المنزلية 2026',
    privacy: 'سياسة الخصوصية',
    terms: 'شروط الاستخدام',
    companyDescription: 'نقدّم خدمات رعاية صحية منزلية موثوقة باحترافية وجودة عالية، لنمنح مرضانا رعاية متكاملة داخل منازلهم بكل راحة وأمان.',
    whyJoinTOUs: 'هل تريد الانضمام لفريقنا؟',
    whyJoinTOUsDescription: 'نبحث دائماً عن المواهب المتميزة للانضمام إلى فريقنا',
    // Form keys
    together: 'معًا',
    whyJoinUs: 'لماذا تنضم إلينا؟',
    joinUsDescription: 'انضم لفريقنا في الرعاية الصحية المنزلية وكن جزءًا من بيئة عمل ملهمة، تضمن لك التطور المهني، الدعم المستمر، وفرص حقيقية للنمو.',
    applyNow: 'قدم الآن',
    nameLabel: 'الاسم',
    phoneLabel: 'الهاتف',
    jobTitleLabel: 'الوظيفة',
    messageLabel: 'الرسالة',
    namePlaceholder: 'أدخل اسمك',
    phonePlaceholder: 'أدخل رقم الهاتف',
    jobPlaceholder: 'ادخل نوع الوظيفة',
    messagePlaceholder: 'اكتب رسالتك',
    uploadCvPdf: 'رفع السيرة الذاتية (PDF)',
    uploadFilesOptional: 'إرفاق ملفات (اختياري)',
    clickToUpload: 'اضغط لرفع ملفات',
    multipleFiles: 'بإمكانك ارفاق عدة ملفات',
    submit: 'إرسال',
    sendMessage: 'أرسل لنا رسالة',
    saudiCode: '966+',
    fillName: 'املأ الاسم',
    fillPhone: 'املأ الهاتف',
    numbersOnly: 'أدخل أرقام فقط',
    phoneNineDigits: 'يجب أن يكون الرقم 9 أرقام بالضبط',
    fillJob: 'املأ الوظيفة',
    fillMessage: 'املأ الرسالة',
    requestReceived: 'لقد تلقينا طلبك',
    messageReceived: 'لقد تلقينا رسالتك',
    teamWillContact: 'فريقنا سوف يتواصل معك قريباً',
    riyadhAddress: 'الرياض، المملكة العربية السعودية',
    // Care component keys
    reliableCare: 'رعاية موثوقة',
    safeServices: 'خدمات صحية منزلية آمنة وموثوقة لجميع عملائنا.',
    qualitySafety: 'جودة وأمان أولويتنا',
    highStandards: 'نلتزم بأعلى معايير الجودة والسلامة في كل خدمة.',
    constantCommunication: 'تواصل دائم وسريع',
    quickResponse: 'استجابة فعالة وسريعة لجميع احتياجات المرضى وعائلاتهم.',
    continuousDevelopment: 'تطوير مستمر',
    latestTech: 'نحرص على تطوير خدماتنا باستمرار باستخدام أحدث التقنيات الطبية',
    fillterAll: 'الكل',
    fillterTech: 'مقالات تقنية',
    fillterCompany: 'اخبار الشركة',
    fillterUpdates: 'أخر المستجدات',
relatedTopics: 'مواضيع ذات صلة',
    discoverMore: 'استكشف المزيد',
    loading: 'تحميل',
    // Privacy Policy
    privacyPolicyTitle: 'سياسة الخصوصية',
    privacyPolicyIntro: 'في شركة إراف، نلتزم بحماية خصوصية جميع زوار ومستخدمي الموقع، ونعمل على ضمان سرية وأمان البيانات الشخصية التي يتم جمعها من خلال استخدامك لموقعنا الإلكتروني أو عند التواصل معنا عبر النماذج المتاحة.',
    privacyPolicySection1Title: '1. جمع المعلومات',
    privacyPolicySection1Content: 'قد نقوم بجمع بعض المعلومات الشخصية عند استخدامك للموقع أو عند تعبئة النماذج، وتشمل على سبيل المثال لا الحصر:',
    privacyPolicySection1List: ['الاسم الكامل', 'رقم الجوال', 'البريد الإلكتروني', 'المدينة أو العنوان (عند الحاجة)', 'الرسائل أو الاستفسارات المرسلة عبر نموذج التواصل', 'الملفات أو المرفقات التي يتم رفعها من خلال الموقع'],
    privacyPolicySection2Title: '2. كيفية استخدام المعلومات',
    privacyPolicySection2List: ['الرد على الاستفسارات والطلبات المقدمة عبر الموقع', 'تقديم خدمات الرعاية الصحية المنزلية بشكل أكثر كفاءة', 'تحسين تجربة المستخدم داخل الموقع', 'التواصل مع المستخدم بشأن الخدمات أو المواعيد أو المتابعة', 'تطوير وتحسين المحتوى والخدمات المقدمة'],
    privacyPolicySection3Title: '3. حماية البيانات',
    privacyPolicySection3Content: 'نلتزم باتخاذ جميع الإجراءات الفنية والتنظيمية المناسبة لحماية بيانات المستخدمين من الوصول غير المصرح به أو الاستخدام أو التعديل أو الإفصاح غير القانوني.',
    privacyPolicySection4Title: '4. مشاركة المعلومات',
    privacyPolicySection4Content: 'لا نقوم ببيع أو تأجير أو مشاركة البيانات الشخصية الخاصة بالمستخدمين مع أي طرف ثالث إلا في الحالات التالية:',
    privacyPolicySection4List: ['عند وجود موافقة صريحة من المستخدم', 'إذا كان ذلك مطلوبًاursuant الأنظمة والقوانين المعمول بها', 'عند الحاجة لتقديم الخدمة من خلال جهات أو مزودي خدمة معتمدين'],
    privacyPolicySection5Title: '5. ملفات تعريف الارتباط (Cookies)',
    privacyPolicySection5Content: 'قد يستخدم الموقع ملفات تعريف الارتباط لتحسين تجربة التصفح وتحليل أداء الموقع، ويمكن للمستخدم التحكم في إعدادات المتصفح لتعطيلها إذا رغب في ذلك.',
    privacyPolicySection6Title: '6. الروابط الخارجية',
    privacyPolicySection6Content: 'قد يحتوي الموقع على روابط لمواقع خارجية، ونحن غير مسؤولين عن سياسات الخصوصية أو محتوى تلك المواقع، لذا يُنصح بالاطلاع على سياسات الخصوصية الخاصة بها عند زيارتها.',
    privacyPolicySection7Title: '7. تحديث سياسة الخصوصية',
    privacyPolicySection7Content: 'تحتفظ شركة إراف بالحق في تعديل أو تحديث سياسة الخصوصية في أي وقت بما يتناسب مع متطلبات العمل أو التحديثات القانونية، ويتم نشر أي تعديلات على هذه الصفحة، ويعد استمرارك في استخدام الموقع موافقة على التحديثات.',
    // Terms
    termsTitle: 'شروط الاستخدام',
    termsIntro: 'مرحبًا بك في موقع شركة إراف. باستخدامك لهذا الموقع، فإنك توافق على الالتزام بالشروط والأحكام التالية. يرجى قراءة هذه الشروط بعناية قبل استخدام الموقع.',
    termsSection1Title: '1. قبول الشروط',
    termsSection1Content: 'إن دخولك إلى الموقع أو استخدامك لأي من خدماته يعني موافقتك الكاملة على الالتزام بشروط الاستخدام هذه، وفي حال عدم موافقتك على أي جزء منها، يُرجى عدم استخدام الموقع.',
    termsSection2Title: '2. استخدام الموقع',
    termsSection2Content: 'يُسمح باستخدام الموقع للأغراض المشروعة فقط، ويُمنع استخدامه بأي طريقة قد تؤدي إلى:',
    termsSection2List: ['انتهاك حقوق الموقع أو تعطيله أو التأثير على أدائه', 'إرسال بيانات أو ملفات ضارة أو فيروسات', 'إساءة استخدام نماذج التواصل أو إرسال معلومات مضللة', 'محاولة الوصول غير المصرح به إلى أنظمة الموقع أو بياناته'],
    termsSection3Title: '3. المحتوى والمعلومات',
    termsSection3Content: 'جميع المعلومات والمحتويات المعروضة على الموقع، بما في ذلك النصوص والصور والتصاميم والشعارات والخدمات، هي ملك لشركة إراف أو مرخصة لها، ولا يجوز نسخها أو إعادة استخدامها أو نشرها دون إذن مسبق.',
    termsSection4Title: '4. دقة المعلومات',
    termsSection4Content: 'تحرص شركة إراف على أن تكون جميع المعلومات المعروضة دقيقة ومحدثة قدر الإمكان، ومع ذلك لا نضمن خلو المحتوى من الأخطاء أو اكتماله بشكل دائم، ونحتفظ بحق تعديل أو تحديث المحتوى في أي وقت دون إشعار مسبق.',
    termsSection5Title: '5. الخدمات والمواعيد',
    termsSection5Content: 'أي طلب يتم تقديمه عبر الموقع للحصول على خدمة أو استفسار لا يعد تأكيدًا نهائيًا لتقديم الخدمة إلا بعد مراجعة الطلب والتواصل مع المستخدم من قبل فريق العمل.',
    termsSection6Title: '6. المسؤولية',
    termsSection6Content: 'نحن نسعى لتقديم تجربة استخدام موثوقة، إلا أننا لا نتحمل المسؤولية عن:',
    termsSection6List: ['أي أعطال فنية مؤقتة في الموقع', 'انقطاع الخدمة بسبب الصيانة أو التحديثات', 'أي استخدام غير صحيح للمعلومات الواردة في الموقع', 'أي أضرار غير مباشرة تنتج عن سوء استخدام الموقع'],
    termsSection7Title: '7. التعديلات على الشروط',
    termsSection7Content: 'تحتفظ شركة إراف بالحق في تعديل أو تحديث شروط الاستخدام في أي وقت، وتصبح التعديلات نافذة فور نشرها على هذه الصفحة، ويعد استمرارك في استخدام الموقع بعد التحديث موافقة ضمن��ة ع��ى الشروط المعدلة.',
  },
  en: {
    home: 'Home',
    about: 'About',
    services: 'Services',
    departments: 'Departments',
    blog: 'Blog',
    join: 'Join Us',
    contact: 'Contact Us',
    exploreServices: 'Explore Our Services',
    exploreBLogs: 'Explore Our Blogs',
    contactUs: 'Contact Us',
    knowMore: 'Know More',
    arabic: 'Arabic',
    english: 'English',
    siteMap: 'Site Map',
    contactInfo: 'Contact Information',
    followUs: 'Follow Us',
    copyright: 'All Rights Reserved © Araf Home Healthcare Services 2026',
    privacy: 'Privacy Policy',
    terms: 'Terms of Use',
    companyDescription: 'We provide reliable home healthcare services with professionalism and high quality, to give our patients comprehensive care inside their homes with comfort and safety.',
    whyJoinTOUs: 'Do you want to join our team?',
    whyJoinTOUsDescription: 'We are always looking for outstanding talent to join our team',
    // Form keys
    together: 'Together',
    whyJoinUs: 'Why Join Us?',
    joinUsDescription: 'Join our home healthcare team and be part of an inspiring work environment that ensures your professional development, continuous support, and real growth opportunities.',
    applyNow: 'Apply Now',
    nameLabel: 'Name',
    phoneLabel: 'Phone',
    jobTitleLabel: 'Job Title',
    messageLabel: 'Message',
    namePlaceholder: 'Enter your name',
    phonePlaceholder: 'Enter phone number',
    jobPlaceholder: 'Enter job type',
    messagePlaceholder: 'Write your message',
    uploadCvPdf: 'Upload CV (PDF)',
    uploadFilesOptional: 'Attach files (optional)',
    clickToUpload: 'Click to upload files',
    multipleFiles: 'You can attach multiple files',
    submit: 'Submit',
    sendMessage: 'Send us a message',
    saudiCode: '966+',
    fillName: 'Fill name',
    fillPhone: 'Fill phone',
    numbersOnly: 'Enter numbers only',
    phoneNineDigits: 'Phone must be exactly 9 digits',
    fillJob: 'Fill job title',
    fillMessage: 'Fill message',
    requestReceived: 'We received your request',
    messageReceived: 'We received your message',
    teamWillContact: 'Our team will contact you soon',
    riyadhAddress: 'Riyadh, Kingdom of Saudi Arabia',
    // Care component keys
    reliableCare: 'Reliable Care',
    safeServices: 'Safe and reliable home healthcare services for all our clients.',
    qualitySafety: 'Quality and Safety are Our Priority',
    highStandards: 'We adhere to the highest standards of quality and safety in every service.',
    constantCommunication: 'Constant and Fast Communication',
    quickResponse: 'Effective and quick response to all patients and their families needs.',
    continuousDevelopment: 'Continuous Development',
    latestTech: 'We continuously develop our services using the latest medical technologies',
    fillterAll: 'All',
    fillterTech: 'Technical articles',
    fillterCompany: 'Company News',
    fillterUpdates: 'Latest Updates',
relatedTopics: 'Related Topics',
    discoverMore: 'Discover More',
    loading: 'Loading',
    // Privacy Policy
    privacyPolicyTitle: 'Privacy Policy',
    privacyPolicyIntro: 'At Araf Company, we are committed to protecting the privacy of all visitors and users of our website, and we work to ensure the confidentiality and security of personal data collected through your use of our website or when contacting us through the available forms.',
    privacyPolicySection1Title: '1. Information Collection',
    privacyPolicySection1Content: 'We may collect some personal information when you use the site or fill out forms, including but not limited to:',
    privacyPolicySection1List: ['Full name', 'Mobile number', 'Email address', 'City or address (when needed)', 'Messages or inquiries sent via the contact form', 'Files or attachments uploaded through the site'],
    privacyPolicySection2Title: '2. How We Use Information',
    privacyPolicySection2List: ['Responding to inquiries and requests submitted through the site', 'Providing home healthcare services more efficiently', 'Improving user experience on the site', 'Contacting the user regarding services, appointments, or follow-ups', 'Developing and improving content and services provided'],
    privacyPolicySection3Title: '3. Data Protection',
    privacyPolicySection3Content: 'We are committed to taking all appropriate technical and organizational measures to protect user data from unauthorized access, use, modification, or unlawful disclosure.',
    privacyPolicySection4Title: '4. Information Sharing',
    privacyPolicySection4Content: 'We do not sell, rent, or share users\' personal data with any third party except in the following cases:',
    privacyPolicySection4List: ['When there is explicit consent from the user', 'If required by applicable laws and regulations', 'When needed to provide service through authorized parties or service providers'],
    privacyPolicySection5Title: '5. Cookies',
    privacyPolicySection5Content: 'The site may use cookies to improve browsing experience and analyze site performance. Users can control browser settings to disable them if they wish.',
    privacyPolicySection6Title: '6. External Links',
    privacyPolicySection6Content: 'The site may contain links to external sites, and we are not responsible for the privacy policies or content of those sites. It is recommended to review their privacy policies when visiting them.',
    privacyPolicySection7Title: '7. Privacy Policy Updates',
    privacyPolicySection7Content: 'Araf Company reserves the right to modify or update the privacy policy at any time as needed to meet business requirements or legal updates. Any modifications will be posted on this page, and your continued use of the site constitutes acceptance of the updates.',
    // Terms
    termsTitle: 'Terms of Use',
    termsIntro: 'Welcome to Araf Company website. By using this site, you agree to be bound by the following terms and conditions. Please read these terms carefully before using the site.',
    termsSection1Title: '1. Acceptance of Terms',
    termsSection1Content: 'Your access to or use of any of its services means your complete acceptance of these terms of use. If you do not agree to any part of them, please do not use the site.',
    termsSection2Title: '2. Site Usage',
    termsSection2Content: 'The site may only be used for legitimate purposes, and its use is prohibited in any way that may lead to:',
    termsSection2List: ['Violating the site\'s rights or disrupting or affecting its performance', 'Sending harmful data or viruses', 'Misusing contact forms or sending misleading information', 'Attempting unauthorized access to the site\'s systems or data'],
    termsSection3Title: '3. Content and Information',
    termsSection3Content: 'All information and content displayed on the site, including text, images, designs, logos, and services, are owned by Araf Company or licensed to it, and may not be copied, reused, or published without prior permission.',
    termsSection4Title: '4. Information Accuracy',
    termsSection4Content: 'Araf Company strives to ensure that all displayed information is accurate and up-to-date as possible. However, we do not guarantee that the content will always be error-free or complete, and we reserve the right to modify or update content at any time without prior notice.',
    termsSection5Title: '5. Services and Appointments',
    termsSection5Content: 'Any request submitted through the site for a service or inquiry is not considered a final confirmation of service provision until the request is reviewed and the user is contacted by the work team.',
    termsSection6Title: '6. Liability',
    termsSection6Content: 'We strive to provide a reliable user experience, but we are not liable for:',
    termsSection6List: ['Any temporary technical malfunctions of the site', 'Service interruption due to maintenance or updates', 'Any incorrect use of information on the site', 'Any indirect damages resulting from misuse of the site'],
    termsSection7Title: '7. Terms Modifications',
    termsSection7Content: 'Araf Company reserves the right to modify or update the terms of use at any time, and modifications become effective immediately upon posting on this page. Your continued use of the site after updates constitutes implicit acceptance of the modified terms.',
  }
};

